# A generic alembic.ini configuration file.

[alembic]
# path to migration scripts
script_location = app/db/migrations

# template for migration file names, e.g. %%(rev)s_%%(slug)s.py
file_template = %%(rev)s_%%(slug)s

# timezone for generated migration titles, e.g. UTC, US/Eastern
# timezone =

# max length of characters to truncate from version names, used by
# "alembic merge"
# truncate_version_names = off

# set to 'true' to run the environment during
# the 'alembic history' command
# sourceless = false

# The method by which OpenWrite hooks are applied to files.
# This may be 'legacy_writer' or 'ruff'.
# hook_attributes = legacy_writer

# comma separated list of package names that contain alembic
# extensions, e.g. mypackage.mymodule,anotherpackage.anothermodule
# extensions =

# output encoding, defaults to system default
# output_encoding = utf-8

sqlalchemy.url = sqlite:///./test.db


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for
# details and examples.
#
# hooks =
# options.hook_name = value
#
# An example hook that runs "ruff":
# ruff = true
# options.ruff_hook_binary = /path/to/ruff
# options.ruff_hook_options = --fix


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%H:%%M:%%S
