default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: pingkong_dev

test:
  <<: *default
  database: pingkong_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails # Keep production separate, will use ENV vars
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  database: pingkong # Keep production separate
  # host: <%= ENV['DATABASE_HOST'] %> # Production host likely from ENV
